library(maps)
#map("world", region="Germany")
map("usa",xlim=c(-130,-60))
#set.seed(NULL)
#dfPoints <-data.frame(long = 10 + runif(10, -2, 2), lat = 50 + runif(10, -2, 4))
cities <- read_csv("GraphGA/cities/cities_us20.csv")
points(x=cities$Long, y = cities$Lat, col = "red")
#lines(x = dfPoints$long, y = dfPoints$lat, col = "blue")
lines(x=dfPoints$long[0:2], y = dfPoints$lat[0:2])
lines(x=dfPoints$long[1:3], y = dfPoints$lat[1:3])
